mode: auto
silent: false
branchName: "${issue.number}/${issue.title,}"
autoCloseIssue: true
gitSafeReplacementChar: "-"
branches:
  - label: enhancement
    prefix: feat/
  - label: bug
    prefix: fix/
  - label: chore
    prefix: chore/
  - label: documentation
    prefix: docs/
  - label: "*"
    skip: true
